#!/bin/bash

# Install Git LFS
# echo "Installing Git LFS..."
# git lfs install
#
# # Track large files (replace with your actual file paths)
# echo "Tracking large files..."
# git lfs track ".terraform/providers/registry.terraform.io/hashicorp/aws/5.96.0/linux_amd64/terraform-provider-aws_v5.96.0_x5"
#
# # Add .gitattributes file generated by Git LFS
# echo "Adding .gitattributes file..."
# git add .gitattributes
#
# # Add the file(s) you want to track and commit the changes
# echo "Adding large file to staging..."
# git add .
#
# # Commit the changes
# echo "Committing the changes..."
# git commit -m "Added large files to LFS"
#
# # Push the changes to remote repository
# echo "Pushing changes to remote repository..."
# git push origin master
#
# echo "Done!"
#
