name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Jab master branch par push hoga
  pull_request:
    branches:
      - master  # Jab master branch par pull request banega

jobs:
  build:
    runs-on: ubuntu-latest  # Ya koi aur runner jo aap use kar rahe ho

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Code ko checkout karne ke liye

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Agar Python use kar rahe hain

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Required dependencies install karna

      - name: Run tests
        run: |
          pytest  # Tests ko run karne ka command

      - name: Deploy
        run: |
          echo "Deploying to production server..."
          # Yahan apni deployment script likhein

