name: Another CI/CD Pipeline

on:
  push:
    branches:
      - feature-branch
  pull_request:
    branches:
      - feature-branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run test script
        run: echo "Running tests!"

